version: '3.5'

services:
    bill_dev:
        container_name: 'bill_dev'
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
